tasks:
- id: 0
  name: leg_right
  pick:
    orientation: [0.9238795325112867, 0.3826834323650898, -2.3432602026631493e-17,
      5.657130561438501e-17]
    pos: [0.55, 0.15, 0.0649999999999994]
  place:
    orientation: [0.9238795325112867, 0.3826834323650898, -2.3432602026631493e-17,
      5.657130561438501e-17]
    pos: [0.35, -0.03, 0.069999999999994]
- id: 1
  name: leg_left
  pick:
    orientation: [0.9238795325112867, 0.3826834323650898, -2.3432602026631493e-17,
      5.657130561438501e-17]
    pos: [0.55, 0.25, 0.09649999999999994]
  place:
    orientation: [0.9238795325112867, 0.3826834323650898, -2.3432602026631493e-17,
      5.657130561438501e-17]
    pos: [0.35, 0.03, 0.09649999999999994]
- id: 2
  name: hips
  pick:
    orientation: [0.9238795325112867, 0.3826834323650898, -2.3432602026631493e-17,
      5.657130561438501e-17]
    pos: [0.55, -0.26849999999999996, 0.035]
  place:
    orientation: [0.9238795325112867, 0.3826834323650898, -2.3432602026631493e-17,
      5.657130561438501e-17]
    pos: [0.35, 0.0315, 0.025]
- id: 3
  name: torso
  pick:
    orientation: [0.9238795325112867, 0.3826834323650898, -2.3432602026631493e-17,
      5.657130561438501e-17]
    pos: [0.55, -0.0975, 0.035]
  place:
    orientation: [0.9238795325112867, 0.3826834323650898, -2.3432602026631493e-17,
      5.657130561438501e-17]
    pos: [0.35, 0.0525, 0.0549999999999999]
- id: 4
  name: hand_right
  pick:
    orientation: [0.9238795325112867, 0.3826834323650898, -2.3432602026631493e-17,
      5.657130561438501e-17]
    pos: [0.62, -0.15, 0.035]
  place:
    orientation: [0.9238795325112867, 0.3826834323650898, -2.3432602026631493e-17,
      5.657130561438501e-17]
    pos: [0.35, -0.06, 0.085]
- id: 5
  name: hand_left
  pick:
    orientation: [0.9238795325112867, 0.3826834323650898, -2.3432602026631493e-17,
      5.657130561438501e-17]
    pos: [0.62, 0.15, 0.435]
  place:
    orientation: [0.9238795325112867, 0.3826834323650898, -2.3432602026631493e-17,
      5.657130561438501e-17]
    pos: [0.35, 0.06, 0.585]
- id: 6
  name: head
  pick:
    orientation: [0.9238795325112867, 0.3826834323650898, -2.3432602026631493e-17,
      5.657130561438501e-17]
    pos: [0.62, 0.0, 0.49649999999999994]
  place:
    orientation: [0.9238795325112867, 0.3826834323650898, -2.3432602026631493e-17,
      5.657130561438501e-17]
    pos: [0.35, 0.0, 0.6465]
